name: 'Deploy to Launchpad'
author: 'Stefan Löffler'
description: 'Upload packages to Launchpad PPAs'

inputs:
  changes_files:
    description: 'space-separated list of paths to .changes files to upload'
    required: true
  repo:
    description: 'PPA to upload to (e.g., ssh-ppa:testuser/nightlies)'
    required: true

runs:
  using: composite
  steps:
    - run: |
        echo """[ssh-ppa]
        login = st.loeffler""" > ~/.dput.cf
        for FILE in ${{ inputs.changes_files }}; do
          echo "::group::Uploading ${FILE}"
          dput "${{ inputs.repo }}" "$FILE"
          echo "::endgroup::"
        done
      shell: bash
