# Simple Rakefile for generating documentation from the CMake build system using
# Rocco:
#
#    http://rtomayko.github.com/rocco
#
require "pathname"
require "rocco/tasks" # Not used, but implicitly tests that Rocco is installed.

# Run everything from the project root directory.
DOC_DIR = Pathname.new(__FILE__).realpath.dirname
DOC_OUTPUT_DIR = DOC_DIR + "html" + "docs"
ROOT_DIR = DOC_DIR + ".." + ".."
Dir.chdir ROOT_DIR

# Gather all CMake files.
CMAKE_FILES = Dir['**/CMakeLists.txt'] + Dir['**/*.cmake.in']

# Remove unwanted items like 'modules/' and 'poppler-data-*/'.
CMAKE_FILES.reject! { |f| f.start_with?("modules/", "poppler-data-") }

# Make document generation the default task.
task :default => [:docs]

# Remove generated documentation files.
task :clean do
  html_files = Dir.chdir(DOC_OUTPUT_DIR) { Dir["**/*.html"] }
  next if html_files.empty?

  puts "Cleaning '#{DOC_OUTPUT_DIR}' (#{html_files.count} files):"
  html_files.each do |f|
    abs_f = DOC_OUTPUT_DIR + f
    if abs_f.file? then
      puts "  * #{f}"
      abs_f.delete
    else
      puts "  ! #{f} is not a file"
    end
  end
end

# Generate documentation from comments in CMake files, but clean up first.
task :docs => [:clean] do
  sh "rocco",
    "--language=cmake",
    "--output=#{DOC_OUTPUT_DIR}",
    "--template=#{DOC_DIR + 'layout.mustache'}",
    *CMAKE_FILES
end

# Generate documentation and then view it.
task :view => [:docs] do
  sh "open",
    "#{DOC_DIR + 'html' + 'index.html'}"
end
