name: 'Set up build environment for TeXworks for Windows'
author: 'Stefan Löffler'
description: ''

runs:
  using: composite
  steps:
    - name: Install MXE
      shell: wsl-bash {0}
      run: |
        sudo sed -ie 's/main$/main universe/' /etc/apt/sources.list
        sudo apt update
        sudo apt install --assume-yes --no-install-recommends cmake git libgdk-pixbuf2.0-dev lzip make patch python-is-python3 wget xz-utils zip
        wget -O /tmp/mxe-texworks.tar.xz https://github.com/stloeffler/mxe/releases/latest/download/mxe-texworks.tar.xz
        sudo mkdir -p /usr/lib/mxe
        tar -C /usr/lib/mxe --xz -xf /tmp/mxe-texworks.tar.xz
        sudo chmod --recursive a+w /usr/lib/mxe
        rm -f "/usr/lib/mxe/usr/i686-w64-mingw32.static/share/cmake/mxe-conf.d/ccache.cmake"

    - name: Build poppler
      shell: wsl-bash {0}
      run: |
        rm -f /usr/lib/mxe/src/poppler*
        cp .github/actions/setup-windows/mxe/poppler* /usr/lib/mxe/src/
        cd /usr/lib/mxe
        make download-only-poppler
        make build-only-poppler_i686-w64-mingw32.static

