name: 'Set up build environment for TeXworks for Windows'
author: 'Stefan Löffler'
description: ''

inputs:
  qt:
    description: 'Qt major version to install (e.g., 5 or 6)'
    required: true

runs:
  using: composite
  steps:
    - name: Install MXE
      shell: wsl-bash {0}
      run: |
        sudo sed -ie 's/main$/main universe/' /etc/apt/sources.list
        sudo apt update
        sudo apt install --assume-yes --no-install-recommends cmake git libgdk-pixbuf2.0-dev lzip make patch python-is-python3 wget xz-utils zip
        wget -O /tmp/mxe-texworks.tar.xz https://github.com/stloeffler/mxe/releases/latest/download/mxe-texworks-qt${{ inputs.qt }}.tar.xz
        sudo mkdir -p /usr/lib/mxe
        tar -C /usr/lib/mxe --xz -xf /tmp/mxe-texworks.tar.xz
        sudo chmod --recursive a+w /usr/lib/mxe
        rm -f "/usr/lib/mxe/usr/i686-w64-mingw32.static/share/cmake/mxe-conf.d/ccache.cmake"
        # Work around https://gitlab.com/libtiff/libtiff/-/issues/528
        sed -ie '/Libs.private\: -lwebp -lzstd -llzma -ljpeg -lz/d' /usr/lib/mxe/usr/i686-w64-mingw32.static/lib/pkgconfig/libtiff-4.pc

    - name: Build poppler
      shell: wsl-bash {0}
      run: |
        rm -f /usr/lib/mxe/src/poppler*
        cp .github/actions/setup-windows/mxe/poppler* /usr/lib/mxe/src/
        ln -s poppler-1-win32.patch /usr/lib/mxe/src/poppler-qt${{ inputs.qt }}-1-win32.patch
        cd /usr/lib/mxe
        make download-only-poppler download-only-poppler-qt${{ inputs.qt }}
        make build-only-poppler_i686-w64-mingw32.static build-only-poppler-qt${{ inputs.qt }}_i686-w64-mingw32.static

