FROM archlinux

RUN pacman --noconfirm -Syu \
	cmake \
	gcc \
	git \
	make \
	hunspell \
	lua \
	poppler-qt6 \
	qt6-5compat \
	qt6-base \
	qt6-declarative \
	qt6-tools \
	gsfonts \
	poppler-data \
	xorg-server-xvfb \
&& pacman --noconfirm -Scc

COPY . /home/tw

RUN mkdir /home/tw/build && cd /home/tw/build && \
cmake -DQT_DEFAULT_MAJOR_VERSION=6 .. && \
make && \
xvfb-run ctest -V
